server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbtest
  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  jpa.show-sql: true